version: '3.0'
networks:
  elk:
    driver: bridge

volumes:
  esdata:

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/config/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - elk

  logstash:
    container_name: logstash
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
      - "5045:5045"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      - elk
    depends_on:
      - elasticsearch

#  fpm:
#    container_name: fpm
#    image: php:fpm
#    ports:
#        - "9000:9000"
#    networks:
#      - elk
#    volumes:
#      - handesk:/var/www/handesk

  nginx:
    container_name: nginx
    build:
      context: nginx/
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - ./opt/:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - elk
    depends_on:
      - kibana
      - handesk
      - fouroneone


  fouroneone:
    container_name: fouroneone
    build: 411-web/
    networks:
      - elk
    command:
      - /apache2-foreground.sh
    depends_on:
      - mysql

  fouroneonecron:
    container_name: fouroneonecron
    build: 411-web/
    networks:
      - elk
    command:
      - /cron-entrypoint.sh
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build:
      context: mysql/
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - elk
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"

  metricbeat:
    container_name: metricbeat
    build:
      context: metricbeat/
    networks:
      - elk
    depends_on:
      - logstash

  handesk:
    container_name: handesk
    build:
      context: handesk/
    environment:
      MYSQL_ROOT_PASSWORD: example
    depends_on:
      - mysql
    networks:
      - elk