version: '3'
services:
  ###
  # Primary Services
  ###
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      HOSTNAME: "elasticsearch"
    networks:
      - elk

  logstash:
    container_name: logstash
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
      - "5045:5045"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      - elk
    depends_on:
      - elasticsearch

  nginx:
    container_name: nginx
    build:
      context: nginx/
    environment:
      - APPLICATION_URL=http://docker.local
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - ./opt/:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - elk
    depends_on:
      - kibana
      - fouroneoneweb
#      - fir

  fouroneoneweb:
    container_name: fouroneone
    build: 411-web/
    networks:
      - elk
    depends_on:
      - mysql

  fouroneonecron:
    container_name: 411cron
    build: 411-cron/
    networks:
      - elk
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build:
      context: Mysql/
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fouroneone
      MYSQL_USER: fouroneone
      MYSQL_PASSWORD: fouroneone
    networks:
    - elk
    volumes:
    - ./MySQL/sql/db_mysql.sql:/docker-entrypoint-initdb.d/01-fouroneoned_db.sql:ro
    ports:
    - "3306:3306"


  metricbeat:
    container_name: metricbeat
    build:
      context: metricbeat/
    networks:
      - elk
    depends_on:
      - logstash

  setup:
    container_name: setup
    build:
      context: setup/
    networks:
      - elk
    depends_on:
      - elasticsearch



#  fir:
#    container_name: fir
#    build:
#      context: fir/
#    networks:
#      - elk

networks:
  elk:
    driver: bridge

volumes:
  esdata:
  esdata1: