version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch-cluster.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      HOSTNAME: "elasticsearch"
    networks:
      - elk

  elasticsearch1:
    container_name: elasticsearch1
    build:
      context: elasticsearch/
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch-cluster.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      HOSTNAME: "elasticsearch1"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
      - "5045:5045"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      - elk
    depends_on:
      - elasticsearch

  nginx:
    container_name: nginx
    build:
      context: nginx/
    environment:
      - APPLICATION_URL=http://docker.local
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
      - ./opt/:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - elk
    depends_on:
      - kibana
      - fir

  metricbeat:
    container_name: metricbeat
    build:
      context: metricbeat/
    networks:
      - elk
    depends_on:
      - logstash

  setup:
    container_name: setup
    build:
      context: utility-manager/
    volumes:
      - ./elasticsearch/templates/:/tools/es/:ro
    networks:
      - elk
    depends_on:
      - elasticsearch

  fir:
    container_name: fir
    build:
      context: fir/
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  esdata:
  esdata1: